async function main() {
  //
}

main().catch((err) => {
  console.error(err)
})
